#pragma once

#define VAPORPLANE_PROJECT_FORMAT_NAME "vaporplane.project"
#define VAPORPLANE_PROJECT_FORMAT_VERSION 4
#define VAPORPLANE_SURFACES_FORMAT_NAME "vaporplane.surfaces"
#define VAPORPLANE_SURFACES_FORMAT_VERSION 2
#define VAPORPLANE_PROJECT_BUNDLE_SUFFIX ".vapor"
#define VAPORPLANE_PROJECT_MANIFEST_FILENAME "project.json"
#define VAPORPLANE_PROJECT_TIMELINE_FILENAME "timeline.mid"
#define VAPORPLANE_PROJECT_SURFACES_FILENAME "surfaces.json"
#define VAPORPLANE_PROJECT_PREVIEW_FILENAME "preview.wav"
#define VAPORPLANE_PROJECT_SAMPLES_DIRNAME "samples"
#define VAPORPLANE_PROJECT_PATTERNS_DIRNAME "patterns"
#define VAPORPLANE_PROJECT_SAMPLE_RATE 48000
#define VAPORPLANE_PROJECT_CHANNELS 2
#define VAPORPLANE_PROJECT_WAV_BITS_PER_SAMPLE 32
