#pragma once

#define VAPORPLANE_PROJECT_FORMAT_NAME "vaporplane.project"
#define VAPORPLANE_PROJECT_FORMAT_VERSION 1
#define VAPORPLANE_SURFACES_FORMAT_NAME "vaporplane.surfaces"
#define VAPORPLANE_SURFACES_FORMAT_VERSION 1
#define VAPORPLANE_PROJECT_BUNDLE_SUFFIX ".vapor"
#define VAPORPLANE_PROJECT_MANIFEST_FILENAME "project.json"
#define VAPORPLANE_PROJECT_TIMELINE_FILENAME "timeline.mid"
#define VAPORPLANE_PROJECT_SURFACES_FILENAME "surfaces.json"
#define VAPORPLANE_PROJECT_SAMPLES_DIRNAME "samples"
