#pragma once

#define VAPORPLANE_PROJECT_FORMAT_VERSION 1
#define VAPORPLANE_PROJECT_EXTENSION ".vapor"
#define VAPORPLANE_PROJECT_MANIFEST_FILENAME "project.json"
#define VAPORPLANE_PROJECT_TIMELINE_FILENAME "timeline.mid"
#define VAPORPLANE_PROJECT_SURFACES_FILENAME "surfaces.json"
#define VAPORPLANE_PROJECT_SAMPLES_DIRNAME "samples"

